services:
  postgres:
    image: postgres:15-alpine
    container_name: sds_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: avantages_sportifs
      POSTGRES_USER: sds_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    networks:
      - sds_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sds_admin -d avantages_sportifs"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sds_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - sds_network
    depends_on:
      postgres:
        condition: service_healthy

  kestra_postgres:
    image: postgres:15-alpine
    container_name: sds_kestra_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
    volumes:
      - kestra_postgres_data:/var/lib/postgresql/data
    networks:
      - sds_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kestra -d kestra"]
      interval: 10s
      timeout: 5s
      retries: 5

  kestra:
    image: kestra/kestra:latest
    container_name: sds_kestra
    pull_policy: always
    user: "root"
    command: server standalone
    volumes:
      - kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - C:/Users/User/poc_avantages_sportifs:/app/project
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra_postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: kestra
        kestra:
          server:
            basicAuth:
              enabled: false
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
    ports:
      - "8081:8080"
    networks:
      - sds_network
    depends_on:
      kestra_postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
  kestra_data:
  kestra_postgres_data:

networks:
  sds_network:
    driver: bridge